### ISSUE TITLE
Validator terra

### ISSUE THREAD

**Issue by alireza20072003** [terra-money/validator-profiles#232]

**Comment by Solcarolus** [comment]
Bonjour 

J’ai transférer des Luna sur mon Wallet terra station et est exécuter le protocole local terra donc pas le complet.

mes fond son partit sur une autre adresse et je n’y est plus accès, sur terraseach je le retrouve avec mes fond mais ma question est ce normal et est-ce parce qu’il y a une période de validation par le validator ? Et de combien de temps avant que ça prend. Et cette adresse est-ce ce qu’on appel le pool de récompense. Car c’est mon Wallet qui as envoyez automatiquement mes Luna sur cette adresse qui n’est pas mon main ?

please

**Comment by Solcarolus** [comment]
Ou est partit mon argent luna environ 43 luna, c'est de l'arnaque vraiment
