### ISSUE TITLE
airdrops

### ISSUE THREAD

**Issue by garyg1234** [terra-money/validator-profiles#273]
I was under the impression I should be getting airdrops for staking with you?  Is this correct?  If so where are they?

**Comment by Boobie84** [comment]
@I was under the impression I should be getting airdrops for staking with you? Is this correct? If so where are they?

**Comment by Boobie84** [comment]
> @i was under the impression I should be getting airdrops for staking with you? Is this correct? If so where are they?

**Comment by Jared-Warn** [comment]
not related to this repo.
