### ISSUE TITLE
Some validators have malformated profile.json

### ISSUE THREAD

**Issue by etienne-napoleone** [terra-money/validator-profiles#50]
[Example](https://github.com/terra-project/validator-profiles/blob/master/validators/terravaloper175hhkyxmkp8hf2zrzka7cnn7lk6mudtv4uuu64/profile.json) -> trailing comma

**Comment by izzyhudson43** [comment]
Except

**Comment by ouiliame** [comment]
Should we add JSON Schema validation + CI ?

**Comment by Jared-Warn** [comment]
issue 2 years old

**Comment by etienne-napoleone** [comment]
it's not fixed tho

**Comment by RomainLanz** [comment]
Would be better to do the same that as been done in [terra-money/assets](https://github.com/terra-money/assets). Migrate to `*.js` file and output JSON with the CI.
