### ISSUE TITLE
Logo not updated 

### ISSUE THREAD

**Issue by Mechwarrior20** [terra-money/validator-profiles#505]
@terran6 thanks for accepting my PR. However the logo I attached has not updated on TS. 

I attach the logo again, please can you have a look at it. 

![2F38C3AD-20D7-4030-AB44-B566585015A1](https://user-images.githubusercontent.com/113836906/190976097-3642efd0-e2cc-4c09-9219-92647e16e62f.jpeg)

**Comment by Jared-TFL** [comment]
Logos in station aren't updated via github.
Please read documentation before running a validator. Closing issue.
