### ISSUE TITLE
I couldn't take the steak off

### ISSUE THREAD

**Issue by Malroili** [terra-money/validator-profiles#507]
I couldn't take the steak off
![072F43E8-DB8D-4997-A44F-9A4719D97AB1](https://user-images.githubusercontent.com/114366128/193408974-6e420c8a-52bf-486f-9066-eda5601f5984.png)
![0554588D-4E9E-4E26-96C0-6D7AD3973BE6](https://user-images.githubusercontent.com/114366128/193408979-c5ac5b15-3f8f-4017-8906-327691c430f9.jpeg)
![Uploading 1F4714BB-B205-4C8D-A191-47020024C0A3.png…]()

**Comment by Malroili** [comment]
I couldn't take the steak off

**Comment by Malroili** [comment]
![Uploading 307E7C31-3E93-42E0-8025-502D47CF6076.png…]()

**Comment by Malroili** [comment]
![57B212FC-DAAA-4159-946E-145FEA832C5C](https://user-images.githubusercontent.com/114366128/193409369-558a067c-cb0b-4d70-a91a-5f120e25e00a.png)
![E6ACD473-0F29-4B82-BCFC-EF1A17B3DA86](https://user-images.githubusercontent.com/114366128/193409371-08cbe0c4-c207-4f84-99f3-b578ec87fe86.png)

**Comment by empire624** [comment]
Me too i same issue occured for me

**Comment by empire624** [comment]
If you had a solution please tell me

**Comment by Jared-TFL** [comment]
This is not the relevant repo for terra station.
Issue looks like user error.
Read documentation on staking here: https://docs.terra.money/learn/terra-station/staking/
Seek assistance here: https://discord.gg/terra-money
