### ISSUE TITLE
profile not showing up in terra station

### ISSUE THREAD

**Issue by echel0n** [terra-money/validator-profiles#535]
Hi,

We recently submitted a pull request (https://github.com/terra-money/validator-profiles/pull/520) and it was approved / merged, however we still do not see our profile or logo in Terra Station, and yes, we did update our identity with our keybase.io PGP key but still nothing, please take a further look into this.

Thanks!

**Comment by wils81ouwehand** [comment]
Yo ik heb geen idee  hoe dit allemaal werkt hoe lost ik het probleem op

**Comment by Panvasi** [comment]
This issue is not only on TR validator.

**Comment by echel0n** [comment]
profile now appears

**Comment by Panvasi** [comment]
> profile now appears

Thanks :)
