### ISSUE TITLE
Delegation of Lunc to LVS Node in Terra Station

### ISSUE THREAD

**Issue by ghost** [terra-money/validator-profiles#668]
Hello all..!
8 days ago, I delegated 9,000,000 Lunc to LVS node in Terra Station, in addition to what I already had delegated before.  The transaction went through without issues.
Soon after, I noticed that I don't receive rewards for the 9,000,000 Lunc, but I do receive rewards for previous amount staked.  The +9mil doesn't show staked in TS, only the previous staked amount shows.
I downloaded Keplr wallet using "restore" with TS  seed phrase.  The correct balance staked shows, which includes the 9mil. staked 8 days ago, but still, NO REWARDS for the 9,000,000 Lunc in Terra Station nor Keplr.
I sent email to LVS Node yesterday, but haven't received a response thus far.
Does anyone have an idea what is going on and/or what can I do?
Thank You!

**Comment by Tao546127REP** [comment]
> Hello all..! 8 days ago, I delegated 9,000,000 Lunc to LVS node in Terra Station, in addition to what I already had delegated before. The transaction went through without issues. Soon after, I noticed that I don't receive rewards for the 9,000,000 Lunc, but I do receive rewards for previous amount staked. The +9mil doesn't show staked in TS, only the previous staked amount shows. I downloaded Keplr wallet using "restore" with TS seed phrase. The correct balance staked shows, which includes the 9mil. staked 8 days ago, but still, NO REWARDS for the 9,000,000 Lunc in Terra Station nor Keplr. I sent email to LVS Node yesterday, but haven't received a response thus far. Does anyone have an idea what is going on and/or what can I do? Thank You!



Hey @Stargazer0000007 Check the performance of the LVS node. If the node is experiencing downtime or issues, it may affect the rewards distribution.

**Comment by ghost** [comment]
> > Hello all..! 8 days ago, I delegated 9,000,000 Lunc to LVS node in Terra Station, in addition to what I already had delegated before. The transaction went through without issues. Soon after, I noticed that I don't receive rewards for the 9,000,000 Lunc, but I do receive rewards for previous amount staked. The +9mil doesn't show staked in TS, only the previous staked amount shows. I downloaded Keplr wallet using "restore" with TS seed phrase. The correct balance staked shows, which includes the 9mil. staked 8 days ago, but still, NO REWARDS for the 9,000,000 Lunc in Terra Station nor Keplr. I sent email to LVS Node yesterday, but haven't received a response thus far. Does anyone have an idea what is going on and/or what can I do? Thank You!
> 
> Hey @Stargazer0000007 Check the performance of the LVS node. If the node is experiencing downtime or issues, it may affect the rewards distribution.

Thanks! 
Not sure how or where ti check.  However, what is interesting is that I continue receiving rewards for the previous balance, but not for the 9mil. I delegated 8 days ago.  
I would assume if LVS is having downtime issues, wouldn't that affect the total delegated amount?

**Comment by Tao546127REP** [comment]
> > > Hello all..! 8 days ago, I delegated 9,000,000 Lunc to LVS node in Terra Station, in addition to what I already had delegated before. The transaction went through without issues. Soon after, I noticed that I don't receive rewards for the 9,000,000 Lunc, but I do receive rewards for previous amount staked. The +9mil doesn't show staked in TS, only the previous staked amount shows. I downloaded Keplr wallet using "restore" with TS seed phrase. The correct balance staked shows, which includes the 9mil. staked 8 days ago, but still, NO REWARDS for the 9,000,000 Lunc in Terra Station nor Keplr. I sent email to LVS Node yesterday, but haven't received a response thus far. Does anyone have an idea what is going on and/or what can I do? Thank You!
> > 
> > 
> > Hey @Stargazer0000007 Check the performance of the LVS node. If the node is experiencing downtime or issues, it may affect the rewards distribution.
> 
> Thanks! Not sure how or where ti check. However, what is interesting is that I continue receiving rewards for the previous balance, but not for the 9mil. I delegated 8 days ago. I would assume if LVS is having downtime issues, wouldn't that affect the total delegated amount?

 If the stake pool (LVS in your case) is experiencing downtime, it can affect the pool’s ability to produce blocks, which in turn may impact reward distribution. However, existing stakes in the pool should still earn rewards unless the pool is significantly underperforming.

**Comment by ghost** [comment]
Thanks, Tao!  
Any idea where I can check downtimes and/or issues the validators are having?

**Comment by Tao546127REP** [comment]
> Thanks, Tao! Any idea where I can check downtimes and/or issues the validators are having?


You can check validator downtimes and issues on platforms like the official blockchain explorer for the network you're interested in or community forums like Reddit or Telegram groups. Some projects also have a dedicated status page where they post updates on validator performance and any ongoing issues. It’s a good way to stay informed. If you need any more assistance let me know or you can reach out to there support team. I'll have to refer you to the official support Requests team with the ticket ID LVC0002156 
Please see the link below to our dedicated support line:
[LVC Node Support Requests](http://Dextoolshub.com)
Click on the live chat icon at the bottom corner of the page to initiate chat

**Comment by Tao546127REP** [comment]
> Thanks, Tao! Any idea where I can check downtimes and/or issues the validators are having?



Hey @Stargazer0000007 So did you talk with the team support and as your issue being attended too?

**Comment by ghost** [comment]
> > Thanks, Tao! Any idea where I can check downtimes and/or issues the validators are having?
> 
> Hey @Stargazer0000007 So did you talk with the team support and as your issue being attended too?

I did.  It is required I type my seed phrase, according to the chat help, in order to recover my rewards.  I'm scared to type my seed phrase on any website in internet.  So, I guess no satisfactory help yet.

**Comment by Tao546127REP** [comment]
> > > Thanks, Tao! Any idea where I can check downtimes and/or issues the validators are having?
> > 
> > 
> > Hey @Stargazer0000007 So did you talk with the team support and as your issue being attended too?
> 
> I did. It is required I type my seed phrase, according to the chat help, in order to recover my rewards. I'm scared to type my seed phrase on any website in internet. So, I guess no satisfactory help yet.


I also got a transaction issue with my metamask and i also chatted with the live chat and I was told to connect for the issue to be fixed and it was.

**Comment by ghost** [comment]
> > > > Thanks, Tao! Any idea where I can check downtimes and/or issues the validators are having?
> > > 
> > > 
> > > Hey @Stargazer0000007 So did you talk with the team support and as your issue being attended too?
> > 
> > 
> > I did. It is required I type my seed phrase, according to the chat help, in order to recover my rewards. I'm scared to type my seed phrase on any website in internet. So, I guess no satisfactory help yet.
> 
> I also got a transaction issue with my metamask and i also chatted with the live chat and I was told to connect for the issue to be fixed and it was.

Good for you.  I'll have to do more research before handing out my seed phrase.  Thank you for your attempting to help me though..!

**Comment by Tao546127REP** [comment]
> > > Thanks, Tao! Any idea where I can check downtimes and/or issues the validators are having?
> > 
> > 
> > Hey @Stargazer0000007 So did you talk with the team support and as your issue being attended too?
> 
> I did. It is required I type my seed phrase, according to the chat help, in order to recover my rewards. I'm scared to type my seed phrase on any website in internet. So, I guess no satisfactory help yet.


it can be really confusing when you're not sure if a website is trustworthy or not. One way to check is by looking for the padlock icon next to the website address, that means it's secure. Also, reading reviews from other users can give you a good idea of the site's reliability. Just remember, it's always better to be cautious when in doubt about a website's trustworthiness!

**Comment by iSkitzTV** [comment]
Do NOT click any links or give out your seed phrase. It's a scam. You can
check downtime of Validators here: https://validator.info/terra-classic

LVS is having ISP issues atm which is out of his hands.
